import { cn } from "@/lib/utils";

/**
 * Banner at the top of a workspace page: brand art behind a Didone headline. The art exists in a
 * light and a dark rendering of the same composition (public/brand/art, generated by
 * drezivo-local/art/banner.py); CSS shows the one that matches the theme, so nothing flashes.
 */
export function PageHero({
  eyebrow,
  title,
  description,
  children,
  className,
  headingId,
}: {
  eyebrow?: React.ReactNode;
  title: React.ReactNode;
  description?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
  headingId?: string;
}) {
  return (
    <section
      aria-labelledby={headingId}
      className={cn(
        "relative isolate overflow-hidden rounded-ws-card border border-dashboard-border bg-dashboard-surface",
        className,
      )}
    >
      <img
        src="/brand/art/banner-light.webp"
        alt=""
        aria-hidden="true"
        className="ws-art-light absolute inset-0 -z-10 h-full w-full object-cover object-[70%_center]"
      />
      <img
        src="/brand/art/banner-dark.webp"
        alt=""
        aria-hidden="true"
        className="ws-art-dark absolute inset-0 -z-10 h-full w-full object-cover object-[70%_center]"
      />
      {/* Scrim on the text side keeps copy above 4.5:1 wherever the threads cross it. */}
      <span
        aria-hidden="true"
        className="absolute inset-0 -z-10 bg-gradient-to-r from-dashboard-surface via-dashboard-surface/80 to-transparent sm:via-dashboard-surface/60"
      />
      <div className="flex flex-col gap-5 p-5 sm:p-7 lg:flex-row lg:items-end lg:justify-between lg:p-8">
        <div className="max-w-2xl">
          {eyebrow ? (
            <p className="dashboard-eyebrow ws-rise" style={{ "--ws-i": 0 } as React.CSSProperties}>
              {eyebrow}
            </p>
          ) : null}
          <h1
            id={headingId}
            className="ws-rise mt-2 font-display text-ws-hero font-medium leading-[1.04] tracking-[-0.015em] text-dashboard-navy"
            style={{ "--ws-i": 1 } as React.CSSProperties}
          >
            {title}
          </h1>
          {description ? (
            <p
              className="ws-rise mt-3 max-w-xl text-ws-body leading-relaxed text-dashboard-muted"
              style={{ "--ws-i": 2 } as React.CSSProperties}
            >
              {description}
            </p>
          ) : null}
          <span aria-hidden="true" className="ws-rule mt-5 block h-0.5 w-24 rounded-full bg-gradient-to-r from-dashboard-accent to-transparent" />
        </div>
        {children ? (
          <div className="ws-rise flex flex-wrap items-center gap-2" style={{ "--ws-i": 3 } as React.CSSProperties}>
            {children}
          </div>
        ) : null}
      </div>
    </section>
  );
}
